version: '3.7'
services:
  web:
    build:
      context: .
    expose:
      - '3000'
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro,z
      - ./certbot/www:/var/www/certbot/:ro,z
      - ./certbot/conf/:/etc/nginx/ssl/:ro,z
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw,z
      - ./certbot/conf/:/etc/letsencrypt/:rw,z
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
