version: '3.7'
services:
  web:
    build:
      context: .
    ports:
      - 3000:3000
  api:
    build:
      context: resumedataapi
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic -c --no-input &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - "db"
    volumes:
      - static_volume:/app/static:z
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/:z
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro,z
      - ./certbot/www:/var/www/certbot/:ro,z
      - ./certbot/conf/:/etc/nginx/ssl/:ro,z
      - static_volume:/home/app/resumedataapi/static:z
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw,z
      - ./certbot/conf/:/etc/letsencrypt/:rw,z
volumes:
  postgres_data:
  static_volume:
