rss = ["https://rss.beehiiv.com/feeds/DAqOWBaHM7.xml"]

[fields]

[fields.designation]
name = "Designation"
content = [
  "DevOps Developer",
  "Platform Developer",
  "Security Software Developer",
  "Full Stack Software Developer",
]

[fields.current_affiliation]
name = "Current Affiliation"
content = "Acre Security"

[fields.pronouns]
name = "Pronouns"
content = "He/Him"

[options]

[options.resume]
text = "Resume"
href = "/resume"

[options.about]
text = "About Me"
href = "/about"

[options.contact]
text = "Contact"
href = "/contact"
