[skills]
software = [
  "AWS",
  "Azure",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Linux",
  # "Django",
  "FastAPI",
  # "Node.js",
  "React",
  "Next.js",
  # "Angular",
  # "Ruby on Rails",
  # "MySQL",
  "PostgreSQL",
  # "SQL",
  "Bash",
  "Git",
]

[skills.programming]
comfortable = ["Python (7yrs)", "TypeScript (4yrs)"]
intermediate = ["Rust (3yrs)", "Java (3yrs)"]
beginner = ["Ruby (1yr)", "Go (3mos)"]

[experience]

[experience.deepcode]
title = "Security Software Engineer"
description = "DeepCode"
date = "02/2025 - 05/2025"
location = "Ottawa, ON"
bulletPoints = [
  "Optimized a data ingestion script using *Python*, *Rust* FFI modules, and *MySQL* batch inserts, processing 1.5 million lines of data in 3 minutes.",
  "Implemented a data processing pipeline using Python async programming, *MQTT*, and *pub-sub* to process and enrich files up to 100 GB/day.",
  "Designed secure cloud architecture for the pipeline using *Terraform* and Azure, ensuring proper access control and network segmentation.",
  # "Wrote a script using *JavaScript* to exfiltrate 2TB of data from *MongoDB* to place into MySQL using async/await and mass insert queries."
]

# [experience.bdo]
# title = "Security Engineer (Co-Op)"
# description = "BDO Canada"
# date = "05/2024 - 07/2024"
# location = "Ottawa, ON"
# bulletPoints = [
#   "Developed a dashboard for monthly reports using *Azure* SIEM data and REST APIs which saved up to 2 hours/report, impacting 18 reports.",
#   "Designed Azure KQL analytics rules and heuristics to detect and analyze over 80 unauthorized login attempts against a Wordpress website.",
#   "Documented GenAI-assisted threat hunting procedures using *Microsoft Copilot*, decreasing SOC resolution time by 31% across 189 tickets.",
# ]

# [experience.innovapost]
# title = "Security Specialist (Co-Op)"
# description = "Innovapost (Now Deloitte)"
# date = "05/2023 - 08/2023"
# location = "Ottawa, ON"
# sar = [
# ]

[experience.barracuda]
title = "Software Engineer (Co-Op)"
description = "Barracuda Networks"
date = "01/2023 - 04/2023"
location = "Ottawa, ON"
bulletPoints = [
  "Designed and implemented a CSV log export system on Windows using *C\\#*, Blazor, and ASP.NET, saving the IT team up to 30 minutes per incident.",
  "Presented selected *AWS* AI services to 5 members of regional leadership, leading to the integration of a new security camera model.",
  "Diagnosed the cause of a failing health check using *Azure Linux* virtual machines and *Docker* tooling, resolving 168 false positive alerts.",
]

[experience.software-secured-pentest]
title = "Application Security Engineer (Co-Op)"
description = "SoftwareSecured"
date = "05/2022 - 08/2022"
location = "Ottawa, ON"
bulletPoints = [
  "Identified a hard-coded secret key in a *Ruby on Rails* microservice API using Semgrep, preventing potential account takeover.",
  "Implemented a *Python* script to check open source vulnerability databases for security issues, saving 8 hours of work over 4 engagements.",
  "Deployed an *AWS* compute instance, confirming an SSRF vulnerability potentially leading to privilege escalation via AWS Lambda.",
]

[experience.software-secured-swe]
title = "Software Engineer (Co-Op)"
description = "SoftwareSecured"
date = "05/2021 - 12/2024"
location = "Ottawa, ON"
bulletPoints = [
  "Implemented an authentication system with SSO and OAuth2 in a *SvelteKit* application using *TypeScript*, mitigating credential breaches.",
  "Managed deployments on *Linux* virtual machines using *Docker Compose*, avoiding environment-based errors that took hours to debug.",
  # "Fixed a broken CI/CD pipeline in *TravisCI* by analyzing logs and cross-referencing source code, unblocking a client.",
  # "Designed a custom metrics dashboard using Angular and d3.js for data visualization surrounding bugs found, including a project heatmap.",
  # "Migrated *JavaScript* visualization code for processing data to a custom *PostgreSQL* query in *Django*, boosting render times by 0.76 seconds.",
  "Built a CVSS calculator integration for a reporting tool using *Django* and *Angular*, saving up to 3 hours per penetration test across 15 clients.",
]

[projects]

[projects.fastctx]
title = "AI Software Engineer"
description = "FastCTX - AI Tinkerers 2025"
date = "07/2025 (1 Day)"
link = "https://devpost.com/software/fastctx"
location = "devpost.com/software/fastctx"
bulletPoints = [
  "Built a back-end server for a codebase visualization tool using *Neo4J* and *LangChain*, allowing developers to see their codebase as a graph.",
  "Added MCP functionality to a *FastAPI* server written in *Python*, allowing integrations with tools like Windsurf and Cursor.",
  "Wrote a *Docker Compose* configuration, including healthchecks and volume specifications to ensure smooth deployments and collaboration.",
]

[projects.cybersci]
title = "Software Engineer"
description = "CyberSci Nationals 2025"
date = "01/2025 - 06/2025"
location = "github.com/CyberSci/PastChallenges/tree/main/challenges/nationals-2024-25"
link = "https://github.com/CyberSCI/PastChallenges/tree/main/challenges/nationals-2024-25"
bulletPoints = [
  "Designed, implemented, and deployed an intentionally vulnerable *SvelteKit* service using the *MQTT* protocol, producing 8 vulnerabilities.",
  "Created stable, reproducible deployment systems for challenges using *Terraform* and *Docker Compose*, resulting in 0 environment-based issues.",
  "Built a test suite of 16 total use cases using *Python* to assess patches during the defence challenge, which ran in under 20 seconds vs. target of 60.",
]

[projects.securevision]
title = "Platform Engineer"
description = "SecureVision - uOttaHack 7"
date = "01/2025 (3 Days)"
location = "dorahacks.io/buidl/21611"
link = "https://dorahacks.io/buidl/21611"
bulletPoints = [
  "Designed the infrastructure and backend for a credential breach management platform using *Terraform*, *Docker*, *Next.js*, and *FastAPI*.",
  "Implemented an event-driven message queue with worker nodes and *Solace pub-sub*, processing 340K+ lines of data using *MQTT*.",
  "Architected a scalable deployment system with Terraform and Docker, allowing up to 128 worker nodes plus web applications and database.",
]

[activities]

[activities.ai-tinkerers]
title = "AI Tinkerers 2025"
timeframe = "07/2025 (1 Day)"
body = "Won Best MCP Agent and Best Async Ambient Agent with FastCTX (#link(\"https://devpost.com/software/fastctx\")[devpost.com/software/fastctx])."

[activities.spurhacks]
title = "SpurHacks 2025"
timeframe = "06/2025 (3 Days)"
body = "Won Best Quantum Startup and Best Web3 Startup with QuantDog (#link(\"https://devpost.com/software/quantdog\")[devpost.com/software/quantdog])."

[activities.cuhacking]
title = "cuHacking 2025"
timeframe = "03/2025 (3 Days)"
body = "Won the QNX sponsor challenge with QNXtainer (#link(\"https://devpost.com/software/qnxtainer\")[devpost.com/software/qnxtainer])."

[activities.owasp-ottawa]
title = "OWASP Ottawa"
timeframe = "02/2025 (1 Day)"
body = "Gave a talk about securing production secrets, including topics like containers, CI/CD, and Terraform."

[activities.uottahack]
title = "uOttaHack 2025"
timeframe = "01/2025 (3 Days)"
body = "Won the DeepCode sponsor challenge with SecureVision (#link(\"https://dorahacks.io/buidl/21611\")[dorahacks.io/buidl/21611])."
