name: Build and Upload Resume

on:
  push:
    branches: [main]
    paths:
      - 'resume/**'
  workflow_dispatch:

jobs:
  build-resume:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: See if dependencies (fonts, AWS CLI, Typst) can be installed simultaneously

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-roboto awscli

      - name: Install specific fonts
        run: sudo scripts/install_fonts.sh

      - name: Install Typst
        run: |
          curl -fsSL https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz | tar -xJ
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/

      - name: Compile resume
        run: |
          scripts/compile_resume.sh

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Robert_Babaev_resume.dev.pdf
      #     path: resume/dev/Robert_Babaev_resume.pdf

      - name: Upload Resume(s)
        env:
          DO_SPACES_ACCESS_KEY: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          DO_SPACES_SECRET_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}
          DO_SPACES_REGION: ${{ vars.DO_SPACES_REGION }}
          DO_SPACES_BUCKET: ${{ vars.DO_SPACES_BUCKET }}
        run: |
          scripts/upload_resume.sh
