name: Build and Upload Resume

on:
  push:
    branches: [main]
    paths:
      - 'resume/'
  workflow_dispatch:

jobs:
  build-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-roboto awscli

      - name: Install specific fonts
        run: |
          set -x

          PROJECT_ROOT=$PWD
          cd $(mktemp -d /tmp/script.XXXXXXX)
          TEMP_DIR=$PWD

          # Install Source Sans Pro (not available in Ubuntu repos)
          cp $PROJECT_ROOT/assets/source_sans_pro.zip .
          unzip source_sans_pro.zip
          sudo mkdir -p /usr/share/fonts/opentype/source-sans-pro
          sudo cp source-sans-2.020R-ro-1.075R-it/OTF/*.otf /usr/share/fonts/opentype/source-sans-pro
          rm -rf ./*

          # Install Source Sans 3 (not available in Ubuntu repos)
          cp $PROJECT_ROOT/assets/Source_Sans_3.zip .
          unzip Source_Sans_3.zip
          sudo mkdir -p /usr/share/fonts/truetype/source-sans-3
          sudo cp *.ttf static/*.ttf /usr/share/fonts/truetype/source-sans-3/
          rm -rf ./*

          # Install FontAwesome 6
          cp $PROJECT_ROOT/assets/fontawesome-free-6.7.2-desktop.zip .
          unzip fontawesome-free-6.7.2-desktop.zip
          sudo mkdir -p /usr/share/fonts/opentype/fontawesome-6
          sudo cp fontawesome-free-6.7.2-desktop/otfs/*.otf /usr/share/fonts/opentype/fontawesome-6
          rm -rf ./*

          # Reload font cache
          sudo fc-cache -f -v

          cd ~
          rm -rf $TEMP_DIR

      - name: Install Typst
        run: |
          curl -fsSL https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz | tar -xJ
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/

      - name: Compile resume
        run: |
          cd resume
          typst compile dev/Robert_Babaev_resume.typ dev/Robert_Babaev_resume.pdf --root .

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Robert_Babaev_resume.dev.pdf
      #     path: resume/dev/Robert_Babaev_resume.pdf

      - name: Configure DO Spaces creds
        env:
          DO_SPACES_ACCESS_KEY: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          DO_SPACES_SECRET_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}
          DO_SPACES_REGION: ${{ vars.DO_SPACES_REGION }}
        run: |
          aws configure set aws_access_key_id $DO_SPACES_ACCESS_KEY
          aws configure set aws_secret_access_key $DO_SPACES_SECRET_KEY
          aws configure set default.region $DO_SPACES_REGION
      - name: Upload resume
        env:
          DO_SPACES_REGION: ${{ vars.DO_SPACES_REGION }}
          DO_SPACES_BUCKET: ${{ vars.DO_SPACES_BUCKET }}
        run: |
          aws s3 cp \
            resume/dev/Robert_Babaev_resume.pdf \
            s3://$DO_SPACES_BUCKET/resumes/dev/Robert_Babaev_resume.pdf \
            --endpoint https://$DO_SPACES_REGION.digitaloceanspaces.com \
            --acl public-read
      # - name: Upload to Digital Ocean Spaces
      #   env:
      #     DO_SPACES_BUCKET: ${{ vars.DO_SPACES_BUCKET }}
      #   run: |
      #     aws --profile do-tor1 s3 cp \
      #       resume/dev/Robert_Babaev_resume.pdf \
      #       s3://$DO_SPACES_BUCKET/resumes/dev/Robert_Babaev_resume.pdf \
      #       --acl public-read
