name: Build and Upload Resume

on:
  push:
    branches: [main]
    paths:
      - 'resume/**'
  workflow_dispatch:

jobs:
  build-resume:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: devenv shell bash -- -e {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: ./.github/actions/devenv-setup
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Compile resume
        run: compile-resume

      - name: Upload Resume(s)
        env:
          DO_SPACES_ACCESS_KEY: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          DO_SPACES_SECRET_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}
        run: upload-resume
