name: Deploy to DigitalOcean

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  TERRAFORM_DIR: terraform

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Install Dependencies'
        run: |
          scripts/install_opentofu.sh --install-method deb

      - name: 'Setup Terraform'
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}
          TF_VAR_do_bucket: ${{ vars.DO_SPACES_BUCKET }}
          TF_VAR_do_region: ${{ vars.DO_SPACES_REGION }}
        run: |
          tofu -version
          cd $TERRAFORM_DIR
          tofu init
          tofu validate

      - name: 'Deploy'
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}
          TF_VAR_do_bucket: ${{ vars.DO_SPACES_BUCKET }}
          TF_VAR_do_region: ${{ vars.DO_SPACES_REGION }}
        run: |
          cd $TERRAFORM_DIR
          tofu plan -out .terraform-plan
          tofu apply .terraform-plan
