name: Run Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test-vitest:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: devenv-ci {0}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Load secrets from Pulumi ESC
        uses: ./.github/actions/pulumi-esc
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          export-environment-variables: CACHIX_AUTH_TOKEN

      - uses: ./.github/actions/devenv-setup

      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile

      - name: Run PNPM tests
        run: pnpm test

      - name: Check build succeeds
        run: pnpm build
