name: Run Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  PUBLIC_DEV_RESUME: https://${{ vars.DO_SPACES_BUCKET }}.${{vars.DO_SPACES_REGION }}.digitaloceanspaces.com/resumes/dev/Robert_Babaev_resume.pdf

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Run PNPM tests
        run: pnpm test

      - name: Check build succeeds
        run: pnpm build
